workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build apk with Flutter
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - gourav@zimo.one
          - arjan@zimo.one
          - mehakdeep@zimo.one
        notify:
          success: true
          failure: true
